--
-- PostgreSQL database dump
--

\restrict Gn0f6b4oKEayeu2Omi6mJdjHVaI2ECk3avyYgGpCRvCqI18uKdyw6bb7MGaDqa1

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    nom character varying(100) NOT NULL,
    post_nom character varying(100) NOT NULL,
    prenom character varying(100) NOT NULL,
    telephone character varying(30) NOT NULL,
    role character varying(20) NOT NULL,
    province_id bigint,
    section_locale_id bigint
);


ALTER TABLE public.accounts_user OWNER TO postgres;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO postgres;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO postgres;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_actionlog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_actionlog (
    id bigint NOT NULL,
    action character varying(100) NOT NULL,
    objet character varying(200) NOT NULL,
    details text NOT NULL,
    ip_address inet,
    path character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.core_actionlog OWNER TO postgres;

--
-- Name: core_actionlog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_actionlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_actionlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_notification (
    id bigint NOT NULL,
    telephone character varying(30) NOT NULL,
    email character varying(254) NOT NULL,
    titre character varying(200) NOT NULL,
    message text NOT NULL,
    canal character varying(10) NOT NULL,
    lu boolean NOT NULL,
    envoye boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    destinataire_id bigint
);


ALTER TABLE public.core_notification OWNER TO postgres;

--
-- Name: core_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: finances_cotisation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.finances_cotisation (
    id bigint NOT NULL,
    montant numeric(12,2) NOT NULL,
    devise character varying(5) NOT NULL,
    date_paiement date NOT NULL,
    type character varying(20) NOT NULL,
    reference character varying(80) NOT NULL,
    mode_paiement character varying(20) NOT NULL,
    notes text NOT NULL,
    date_creation timestamp with time zone NOT NULL,
    enregistre_par_id bigint,
    membre_id bigint NOT NULL,
    preuve character varying(100)
);


ALTER TABLE public.finances_cotisation OWNER TO postgres;

--
-- Name: finances_cotisation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.finances_cotisation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finances_cotisation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: membership_adhesion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.membership_adhesion (
    id bigint NOT NULL,
    nom character varying(100) NOT NULL,
    post_nom character varying(100) NOT NULL,
    prenom character varying(100) NOT NULL,
    date_naissance date NOT NULL,
    lieu_naissance character varying(150) NOT NULL,
    sexe character varying(1) NOT NULL,
    etat_civil character varying(20) NOT NULL,
    adresse character varying(255) NOT NULL,
    telephone character varying(30) NOT NULL,
    email character varying(254) NOT NULL,
    nationalite character varying(80) NOT NULL,
    type_piece_identite character varying(20) NOT NULL,
    numero_piece_identite character varying(80) NOT NULL,
    niveau_etudes character varying(20) NOT NULL,
    profession character varying(120) NOT NULL,
    deja_membre boolean NOT NULL,
    details_membre text NOT NULL,
    motivations text NOT NULL,
    certifie_exactitude boolean NOT NULL,
    date_signature date NOT NULL,
    photo1 character varying(100) NOT NULL,
    photo2 character varying(100) NOT NULL,
    statut character varying(15) NOT NULL,
    numero_membre character varying(30),
    motif_rejet text NOT NULL,
    date_creation timestamp with time zone NOT NULL,
    date_modification timestamp with time zone NOT NULL,
    latitude numeric(9,6),
    longitude numeric(9,6),
    province_origine_id bigint NOT NULL,
    section_locale_id bigint NOT NULL,
    valide_par_id bigint,
    qualite character varying(20) NOT NULL
);


ALTER TABLE public.membership_adhesion OWNER TO postgres;

--
-- Name: membership_adhesion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.membership_adhesion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.membership_adhesion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: membership_cartemembre; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.membership_cartemembre (
    id bigint NOT NULL,
    numero_carte character varying(40) NOT NULL,
    date_emission date NOT NULL,
    date_expiration date NOT NULL,
    qr_code character varying(100) NOT NULL,
    fichier_pdf character varying(100) NOT NULL,
    actif boolean NOT NULL,
    membre_id bigint NOT NULL,
    image_carte character varying(100) NOT NULL
);


ALTER TABLE public.membership_cartemembre OWNER TO postgres;

--
-- Name: membership_cartemembre_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.membership_cartemembre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.membership_cartemembre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: membership_membre; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.membership_membre (
    id bigint NOT NULL,
    actif boolean NOT NULL,
    date_activation timestamp with time zone NOT NULL,
    notes text NOT NULL,
    adhesion_id bigint NOT NULL
);


ALTER TABLE public.membership_membre OWNER TO postgres;

--
-- Name: membership_membre_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.membership_membre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.membership_membre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organisation_affectationpolitique; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organisation_affectationpolitique (
    id bigint NOT NULL,
    role character varying(30) NOT NULL,
    date_debut date NOT NULL,
    date_fin date,
    actif boolean NOT NULL,
    notes text NOT NULL,
    commune_id bigint,
    membre_id bigint NOT NULL,
    province_id bigint,
    section_locale_id bigint
);


ALTER TABLE public.organisation_affectationpolitique OWNER TO postgres;

--
-- Name: organisation_affectationpolitique_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.organisation_affectationpolitique ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organisation_affectationpolitique_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organisation_evenement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.organisation_evenement (
    id bigint NOT NULL,
    titre character varying(200) NOT NULL,
    description text NOT NULL,
    type character varying(20) NOT NULL,
    date timestamp with time zone NOT NULL,
    lieu character varying(255) NOT NULL,
    participants_attendus integer NOT NULL,
    actif boolean NOT NULL,
    date_creation timestamp with time zone NOT NULL,
    organisateur_id bigint,
    province_id bigint,
    section_locale_id bigint,
    CONSTRAINT organisation_evenement_participants_attendus_check CHECK ((participants_attendus >= 0))
);


ALTER TABLE public.organisation_evenement OWNER TO postgres;

--
-- Name: organisation_evenement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.organisation_evenement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organisation_evenement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: territoires_commune; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.territoires_commune (
    id bigint NOT NULL,
    nom character varying(120) NOT NULL,
    slug character varying(140) NOT NULL,
    actif boolean NOT NULL,
    ville_id bigint NOT NULL
);


ALTER TABLE public.territoires_commune OWNER TO postgres;

--
-- Name: territoires_commune_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.territoires_commune ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.territoires_commune_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: territoires_province; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.territoires_province (
    id bigint NOT NULL,
    nom character varying(120) NOT NULL,
    code character varying(10) NOT NULL,
    slug character varying(140) NOT NULL,
    actif boolean NOT NULL
);


ALTER TABLE public.territoires_province OWNER TO postgres;

--
-- Name: territoires_province_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.territoires_province ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.territoires_province_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: territoires_sectionlocale; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.territoires_sectionlocale (
    id bigint NOT NULL,
    nom character varying(150) NOT NULL,
    code character varying(30) NOT NULL,
    adresse character varying(255) NOT NULL,
    telephone character varying(30) NOT NULL,
    actif boolean NOT NULL,
    latitude numeric(9,6),
    longitude numeric(9,6),
    commune_id bigint NOT NULL
);


ALTER TABLE public.territoires_sectionlocale OWNER TO postgres;

--
-- Name: territoires_sectionlocale_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.territoires_sectionlocale ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.territoires_sectionlocale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: territoires_ville; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.territoires_ville (
    id bigint NOT NULL,
    nom character varying(120) NOT NULL,
    slug character varying(140) NOT NULL,
    actif boolean NOT NULL,
    province_id bigint NOT NULL
);


ALTER TABLE public.territoires_ville OWNER TO postgres;

--
-- Name: territoires_ville_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.territoires_ville ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.territoires_ville_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, nom, post_nom, prenom, telephone, role, province_id, section_locale_id) FROM stdin;
1	pbkdf2_sha256$1000000$E5hnJk4F7VKPIwI831R6KG$/KsqyWoJbyIkbrosqsTcSXKUP4giV98YpCVUs0qCdYY=	2026-08-02 13:26:51.896413+00	t	admin			admin@eparti.cd	t	t	2026-07-27 15:15:53.459+00	Admin	National	eParti		ADMIN_NATIONAL	\N	\N
2	pbkdf2_sha256$1000000$Z2OxPTUI2J1eAWKowAEqUa$m+maJ5XFirm2zPBxQPJpyNPqeDwF6F9uLjydYS3Gw/s=	2026-08-02 13:30:30.949724+00	f	Bienvenu			bienvenue@gmail.com	t	t	2026-07-29 16:28:13.464+00	NGAMIKA	EWIRI	Bienvenu	0811508182	LOCAL	1	4
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Utilisateur	6	add_user
22	Can change Utilisateur	6	change_user
23	Can delete Utilisateur	6	delete_user
24	Can view Utilisateur	6	view_user
25	Can add Province	7	add_province
26	Can change Province	7	change_province
27	Can delete Province	7	delete_province
28	Can view Province	7	view_province
29	Can add Ville	8	add_ville
30	Can change Ville	8	change_ville
31	Can delete Ville	8	delete_ville
32	Can view Ville	8	view_ville
33	Can add Commune	9	add_commune
34	Can change Commune	9	change_commune
35	Can delete Commune	9	delete_commune
36	Can view Commune	9	view_commune
37	Can add Section locale	10	add_sectionlocale
38	Can change Section locale	10	change_sectionlocale
39	Can delete Section locale	10	delete_sectionlocale
40	Can view Section locale	10	view_sectionlocale
41	Can add Adhésion	11	add_adhesion
42	Can change Adhésion	11	change_adhesion
43	Can delete Adhésion	11	delete_adhesion
44	Can view Adhésion	11	view_adhesion
45	Can add Membre	12	add_membre
46	Can change Membre	12	change_membre
47	Can delete Membre	12	delete_membre
48	Can view Membre	12	view_membre
49	Can add Carte de membre	13	add_cartemembre
50	Can change Carte de membre	13	change_cartemembre
51	Can delete Carte de membre	13	delete_cartemembre
52	Can view Carte de membre	13	view_cartemembre
53	Can add Cotisation	14	add_cotisation
54	Can change Cotisation	14	change_cotisation
55	Can delete Cotisation	14	delete_cotisation
56	Can view Cotisation	14	view_cotisation
57	Can add Événement	15	add_evenement
58	Can change Événement	15	change_evenement
59	Can delete Événement	15	delete_evenement
60	Can view Événement	15	view_evenement
61	Can add Affectation politique	16	add_affectationpolitique
62	Can change Affectation politique	16	change_affectationpolitique
63	Can delete Affectation politique	16	delete_affectationpolitique
64	Can view Affectation politique	16	view_affectationpolitique
65	Can add Journal d'action	17	add_actionlog
66	Can change Journal d'action	17	change_actionlog
67	Can delete Journal d'action	17	delete_actionlog
68	Can view Journal d'action	17	view_actionlog
69	Can add Notification	18	add_notification
70	Can change Notification	18	change_notification
71	Can delete Notification	18	delete_notification
72	Can view Notification	18	view_notification
\.


--
-- Data for Name: core_actionlog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_actionlog (id, action, objet, details, ip_address, path, created_at, user_id) FROM stdin;
1	POST /accounts/login/		status=302	127.0.0.1	/accounts/login/	2026-07-27 15:27:12.633+00	1
2	POST /adhesions/cartes/1/generer/		status=302	127.0.0.1	/adhesions/cartes/1/generer/	2026-07-27 15:27:36.034+00	1
3	POST /finances/cotisations/nouvelle/		status=302	127.0.0.1	/finances/cotisations/nouvelle/	2026-07-27 15:28:21.495+00	1
4	POST /organisation/evenements/nouveau/		status=302	127.0.0.1	/organisation/evenements/nouveau/	2026-07-27 15:30:07.995+00	1
5	POST /adhesions/cartes/2/generer/		status=302	127.0.0.1	/adhesions/cartes/2/generer/	2026-07-27 15:59:10.836+00	1
6	POST /adhesions/nouvelle/		status=200	127.0.0.1	/adhesions/nouvelle/	2026-07-27 16:18:05.562+00	1
7	POST /adhesions/nouvelle/		status=302	127.0.0.1	/adhesions/nouvelle/	2026-07-27 16:18:27.452+00	1
8	POST /adhesions/3/valider/		status=302	127.0.0.1	/adhesions/3/valider/	2026-07-27 16:19:08.78+00	1
9	POST /adhesions/cartes/3/generer/		status=302	127.0.0.1	/adhesions/cartes/3/generer/	2026-07-27 16:19:19.945+00	1
10	POST /adhesions/cartes/3/generer/		status=302	127.0.0.1	/adhesions/cartes/3/generer/	2026-07-27 16:19:28.414+00	1
11	POST /accounts/login/		status=302	127.0.0.1	/accounts/login/	2026-07-27 16:25:29.074+00	1
12	POST /accounts/login/		status=302	127.0.0.1	/accounts/login/	2026-07-28 15:12:30.999+00	1
13	POST /adhesions/membres/3/modifier/		status=302	127.0.0.1	/adhesions/membres/3/modifier/	2026-07-28 15:17:52.58+00	1
14	POST /adhesions/cartes/3/generer/		status=302	127.0.0.1	/adhesions/cartes/3/generer/	2026-07-28 15:18:16.431+00	1
15	POST /adhesions/nouvelle/		status=302	127.0.0.1	/adhesions/nouvelle/	2026-07-29 16:11:59.025+00	1
16	POST /finances/cotisations/nouvelle/		status=302	127.0.0.1	/finances/cotisations/nouvelle/	2026-07-29 16:13:56.249+00	1
17	POST /adhesions/membres/3/modifier/		status=302	127.0.0.1	/adhesions/membres/3/modifier/	2026-07-29 16:16:10.568+00	1
18	POST /accounts/utilisateurs/nouveau/		status=200	127.0.0.1	/accounts/utilisateurs/nouveau/	2026-07-29 16:27:46.546+00	1
19	POST /accounts/utilisateurs/nouveau/		status=302	127.0.0.1	/accounts/utilisateurs/nouveau/	2026-07-29 16:28:14.015+00	1
20	POST /accounts/login/		status=302	127.0.0.1	/accounts/login/	2026-07-29 16:28:54.285+00	2
21	POST /adhesions/membres/1/modifier/		status=302	127.0.0.1	/adhesions/membres/1/modifier/	2026-07-29 16:30:39.239+00	2
22	POST /adhesions/cartes/1/generer/		status=302	127.0.0.1	/adhesions/cartes/1/generer/	2026-07-29 16:45:21.711+00	2
23	POST /accounts/login/		status=302	127.0.0.1	/accounts/login/	2026-08-01 20:13:18.479+00	1
24	POST /adhesions/cartes/1/generer/		status=302	127.0.0.1	/adhesions/cartes/1/generer/	2026-08-01 20:18:20.395+00	1
25	POST /accounts/login/		status=302	127.0.0.1	/accounts/login/	2026-08-01 20:20:15.388+00	1
26	POST /accounts/login/		status=302	127.0.0.1	/accounts/login/	2026-08-01 20:21:23.838+00	1
27	POST /accounts/utilisateurs/2/modifier/		status=302	127.0.0.1	/accounts/utilisateurs/2/modifier/	2026-08-01 20:21:38.906+00	1
28	POST /accounts/login/		status=302	127.0.0.1	/accounts/login/	2026-08-01 20:21:57.53+00	2
29	POST /adhesions/nouvelle/		status=200	127.0.0.1	/adhesions/nouvelle/	2026-08-01 20:29:13.284+00	2
30	POST /adhesions/nouvelle/		status=302	127.0.0.1	/adhesions/nouvelle/	2026-08-01 20:29:35.613+00	2
31	POST /accounts/login/		status=302	127.0.0.1	/accounts/login/	2026-08-01 20:33:59.265+00	1
32	POST /adhesions/5/valider/		status=302	127.0.0.1	/adhesions/5/valider/	2026-08-01 20:38:48.053+00	1
33	POST /finances/cotisations/nouvelle/		status=302	127.0.0.1	/finances/cotisations/nouvelle/	2026-08-01 20:45:02.131+00	1
34	POST /accounts/utilisateurs/2/modifier/		status=302	127.0.0.1	/accounts/utilisateurs/2/modifier/	2026-08-01 20:45:59.389+00	1
35	POST /adhesions/membres/1/modifier/		status=302	127.0.0.1	/adhesions/membres/1/modifier/	2026-08-01 21:25:36.8+00	1
36	POST /adhesions/membres/1/modifier/		status=302	127.0.0.1	/adhesions/membres/1/modifier/	2026-08-01 21:52:58.728+00	1
37	POST /adhesions/membres/1/modifier/		status=302	127.0.0.1	/adhesions/membres/1/modifier/	2026-08-01 21:53:26.723+00	1
38	POST /adhesions/membres/4/modifier/		status=302	127.0.0.1	/adhesions/membres/4/modifier/	2026-08-01 21:55:55.181+00	1
39	POST /accounts/login/		status=302	127.0.0.1	/accounts/login/	2026-08-01 23:11:42.624+00	1
40	POST /e-parti/accounts/login/		status=302	102.208.120.110	/e-parti/accounts/login/	2026-08-02 11:02:53.866642+00	1
41	POST /e-parti/accounts/login/		status=302	169.159.220.186	/e-parti/accounts/login/	2026-08-02 11:08:54.345339+00	1
42	POST /e-parti/accounts/login/		status=302	102.223.130.19	/e-parti/accounts/login/	2026-08-02 11:15:49.183072+00	1
43	POST /e-parti/accounts/login/		status=302	169.159.212.186	/e-parti/accounts/login/	2026-08-02 11:21:06.216852+00	2
44	POST /e-parti/accounts/login/		status=302	169.159.220.186	/e-parti/accounts/login/	2026-08-02 11:24:39.275145+00	1
45	POST /e-parti/accounts/login/		status=302	102.206.156.152	/e-parti/accounts/login/	2026-08-02 11:27:37.6663+00	1
46	POST /e-parti/accounts/login/		status=302	169.159.212.186	/e-parti/accounts/login/	2026-08-02 11:33:52.765411+00	1
47	POST /e-parti/finances/cotisations/nouvelle/		status=302	169.159.212.186	/e-parti/finances/cotisations/nouvelle/	2026-08-02 11:35:16.200666+00	1
48	POST /e-parti/adhesions/membres/1/modifier/		status=302	102.208.120.110	/e-parti/adhesions/membres/1/modifier/	2026-08-02 12:01:25.176002+00	1
49	POST /e-parti/adhesions/membres/3/modifier/		status=302	102.208.120.110	/e-parti/adhesions/membres/3/modifier/	2026-08-02 12:02:19.440303+00	1
50	POST /e-parti/adhesions/membres/4/modifier/		status=302	102.208.120.110	/e-parti/adhesions/membres/4/modifier/	2026-08-02 12:02:46.436764+00	1
51	POST /e-parti/accounts/login/		status=302	169.159.212.186	/e-parti/accounts/login/	2026-08-02 12:10:07.592521+00	1
52	POST /e-parti/adhesions/6/valider/		status=302	169.159.212.186	/e-parti/adhesions/6/valider/	2026-08-02 12:13:20.723979+00	1
53	POST /e-parti/adhesions/membres/3/modifier/		status=302	169.159.212.186	/e-parti/adhesions/membres/3/modifier/	2026-08-02 12:15:50.72372+00	1
54	POST /e-parti/adhesions/nouvelle/		status=302	169.159.212.186	/e-parti/adhesions/nouvelle/	2026-08-02 12:32:06.468513+00	1
55	POST /e-parti/adhesions/7/valider/		status=302	169.159.212.186	/e-parti/adhesions/7/valider/	2026-08-02 12:32:28.278182+00	1
56	POST /e-parti/accounts/login/		status=302	169.159.212.186	/e-parti/accounts/login/	2026-08-02 12:55:36.45954+00	2
57	POST /e-parti/accounts/login/		status=302	169.159.212.186	/e-parti/accounts/login/	2026-08-02 13:26:51.905576+00	1
58	POST /e-parti/adhesions/4/rejeter/		status=302	169.159.220.186	/e-parti/adhesions/4/rejeter/	2026-08-02 13:29:40.137741+00	1
59	POST /e-parti/accounts/login/		status=302	169.159.220.186	/e-parti/accounts/login/	2026-08-02 13:30:30.963183+00	2
\.


--
-- Data for Name: core_notification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.core_notification (id, telephone, email, titre, message, canal, lu, envoye, created_at, destinataire_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	accounts	user
7	territoires	province
8	territoires	ville
9	territoires	commune
10	territoires	sectionlocale
11	membership	adhesion
12	membership	membre
13	membership	cartemembre
14	finances	cotisation
15	organisation	evenement
16	organisation	affectationpolitique
17	core	actionlog
18	core	notification
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	territoires	0001_initial	2026-08-01 23:27:52.620055+00
2	contenttypes	0001_initial	2026-08-01 23:27:52.637396+00
3	contenttypes	0002_remove_content_type_name	2026-08-01 23:27:52.647933+00
4	auth	0001_initial	2026-08-01 23:27:52.74537+00
5	auth	0002_alter_permission_name_max_length	2026-08-01 23:27:52.752373+00
6	auth	0003_alter_user_email_max_length	2026-08-01 23:27:52.758376+00
7	auth	0004_alter_user_username_opts	2026-08-01 23:27:52.767385+00
8	auth	0005_alter_user_last_login_null	2026-08-01 23:27:52.773034+00
9	auth	0006_require_contenttypes_0002	2026-08-01 23:27:52.775043+00
10	auth	0007_alter_validators_add_error_messages	2026-08-01 23:27:52.78304+00
11	auth	0008_alter_user_username_max_length	2026-08-01 23:27:52.789032+00
12	auth	0009_alter_user_last_name_max_length	2026-08-01 23:27:52.795032+00
13	auth	0010_alter_group_name_max_length	2026-08-01 23:27:52.803036+00
14	auth	0011_update_proxy_permissions	2026-08-01 23:27:52.812034+00
15	auth	0012_alter_user_first_name_max_length	2026-08-01 23:27:52.817058+00
16	accounts	0001_initial	2026-08-01 23:27:52.938099+00
17	admin	0001_initial	2026-08-01 23:27:52.973139+00
18	admin	0002_logentry_remove_auto_add	2026-08-01 23:27:52.983142+00
19	admin	0003_logentry_add_action_flag_choices	2026-08-01 23:27:52.989142+00
20	core	0001_initial	2026-08-01 23:27:53.025735+00
21	membership	0001_initial	2026-08-01 23:27:53.111568+00
22	finances	0001_initial	2026-08-01 23:27:53.140115+00
23	finances	0002_devise_choices	2026-08-01 23:27:53.151846+00
24	membership	0002_cartemembre_image_carte	2026-08-01 23:27:53.158841+00
25	membership	0003_adhesion_domaine_adhesion_federation_and_more	2026-08-01 23:27:53.197079+00
26	membership	0004_remove_carte_modele_fields	2026-08-01 23:27:53.234709+00
27	membership	0005_normalize_numero_membre	2026-08-01 23:27:53.26237+00
28	organisation	0001_initial	2026-08-01 23:27:53.344154+00
29	sessions	0001_initial	2026-08-01 23:27:53.356884+00
30	finances	0003_mode_paiement_choices	2026-08-02 13:43:13.75133+00
31	finances	0004_cotisation_preuve	2026-08-02 13:43:13.787072+00
32	membership	0006_adhesion_qualite	2026-08-02 13:43:13.807247+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
bki4j15wdurcrreecptz7tvj9c3w6n5v	.eJxVjEsOwiAYhO_C2pBCoRSX7j1D87-UqoGktCvj3S1JFzqryXwz81YTbGuatirLNLM6K6NOvxkCPSU3wA_I96Kp5HWZUbeKPmjV18Lyuhzdv4MENe1rR7FzHqm33kiTFX8zgA4oMlk77jYIo0iEQBwiyTB0gmjNCNJ79fkCFtk5eg:1wqTy1:cuVTNRUjQNzUo1f6NnV2k6B9GpfmqqJuZ1MY6NpWSUw	2026-08-16 11:02:53.872355+00
rlybqovjzfj2yfv6hjrkq7et11p2al91	.eJxVjEsOwiAYhO_C2pBCoRSX7j1D87-UqoGktCvj3S1JFzqryXwz81YTbGuatirLNLM6K6NOvxkCPSU3wA_I96Kp5HWZUbeKPmjV18Lyuhzdv4MENe1rR7FzHqm33kiTFX8zgA4oMlk77jYIo0iEQBwiyTB0gmjNCNJ79fkCFtk5eg:1wqUAX:vfc9_KGaWMyR250TcSmUKS661U2sqmT14PH1Em1RJIY	2026-08-16 11:15:49.19806+00
6ljbznseg8uuxciqsor776osp7tni409	.eJxVjEsOwiAYhO_C2pBCoRSX7j1D87-UqoGktCvj3S1JFzqryXwz81YTbGuatirLNLM6K6NOvxkCPSU3wA_I96Kp5HWZUbeKPmjV18Lyuhzdv4MENe1rR7FzHqm33kiTFX8zgA4oMlk77jYIo0iEQBwiyTB0gmjNCNJ79fkCFtk5eg:1wqULx:bKZdiEYSVzhSTmN1JyGT_ZMXzBghYaMKBRjQUuh3-jA	2026-08-16 11:27:37.673606+00
6q7txdsr0r4wba5nuhb2x6xhbhtxyqtd	.eJxVjDsOwyAQBe9CHSHz8QIp0_sMCHaX2ElkJGNXUe4eIblI2jcz7y1iOvY5Ho23uJC4Ci0uv1tO-OS1A3qk9V4l1nXfliy7Ik_a5FSJX7fT_TuYU5t7rZUGm8FToWSVs9oZlQM7E1jj4Ml4HDAwKS5QxgJAasRgAAong0F8vt3GOBg:1wqWGs:sTFfVYgTTRfRheld05GF7wx3ZXAZhhPB_FeY7bMwys4	2026-08-16 13:30:30.970039+00
9ehdtc3h804u9htr79iqmymfbztb1r24	.eJxVjEEOwiAQRe_C2hAo0Cku3XsGMsNMpGogKe3KeHdt0oVu_3vvv1TCbS1p67KkmdVZWXX63QjzQ-oO-I711nRudV1m0ruiD9r1tbE8L4f7d1Cwl28tgBCQiQyIF8lTYGO8Y3AThsH7MRI4Hy1Fi4jMOUIcTHCEYM3oQL0_8AM3mw:1wqSr7:mx9tBFBKjTUJFCthQt2a6bjAJJ5h_AvwMhunmCRu9eg	2026-08-16 09:51:41.763765+00
\.


--
-- Data for Name: finances_cotisation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.finances_cotisation (id, montant, devise, date_paiement, type, reference, mode_paiement, notes, date_creation, enregistre_par_id, membre_id, preuve) FROM stdin;
4	25.00	USD	2026-08-02	mensuelle	Cotisations	especes	Bien	2026-08-02 11:35:16.136092+00	1	3	\N
3	200.00	USD	2026-08-01	exceptionnelle	REF0009	especes	OK	2026-08-01 20:45:02.119+00	1	4	\N
2	200000.00	CDF	2026-07-29	mensuelle	P0011	autre	Paiement recu	2026-07-29 16:13:56.212+00	1	1	\N
1	100000.00	CDF	2026-07-27	mensuelle	P001	mpesa	RAS	2026-07-27 15:28:21.467+00	1	1	\N
\.


--
-- Data for Name: membership_adhesion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.membership_adhesion (id, nom, post_nom, prenom, date_naissance, lieu_naissance, sexe, etat_civil, adresse, telephone, email, nationalite, type_piece_identite, numero_piece_identite, niveau_etudes, profession, deja_membre, details_membre, motivations, certifie_exactitude, date_signature, photo1, photo2, statut, numero_membre, motif_rejet, date_creation, date_modification, latitude, longitude, province_origine_id, section_locale_id, valide_par_id, qualite) FROM stdin;
1	Mukendi	Kabongo	Jeanne	1990-05-12	Kinshasa	M	CELIBATAIRE	Av. de la Libération, Gombe	+243810000001	jean.mukendi@example.cd	Congolaise	CARTE_ELECTEUR	CE-123456789	UNIVERSITAIRE	Enseignant	f		Servir la nation et renforcer la démocratie locale.	t	2026-07-27	adhesions/photos/2026/08/photo1.jpg	adhesions/photos/2026/08/photo1_1NlB4EM.jpg	VALIDE	A000001		2026-07-27 15:15:53.657+00	2026-08-02 12:01:25.068737+00	\N	\N	1	4	1	MEMBRE_EFFECTIF
5	MUTOMBO	DISU	Arman	2016-08-08	KINSHASA	M	MARIE	TSHATSHI 39 Q. LEMERA C/GOMBE	00234818986455	muto@gmail.com	Congolaise	CARTE_ELECTEUR	198192829	UNIVERSITAIRE	LIBERALE	f		APPORTER MON SOUTIENT AU PARTI	t	2026-08-01	adhesions/photos/2026/08/photo2.jpg	adhesions/photos/2026/08/photo2_HYbbBPC.jpg	VALIDE	A000003		2026-08-01 20:29:35.597+00	2026-08-02 12:02:46.304495+00	\N	\N	1	4	1	MEMBRE_EFFECTIF
6	Kambanda	Yila	Merveille	2024-10-03	Idiofa	F	MARIE	Lodja	243850000001	bibiwa@gmail.com	Congolaise	CARTE_ELECTEUR	NN0000278	SECONDAIRE	Fonctionnaire	f		Défendre des valeurs	t	2026-08-02	adhesions/photos/2026/08/IMG-20260728-WA0310.jpg	adhesions/photos/2026/08/IMG-20260728-WA0310_IGMePWq.jpg	VALIDE	000004		2026-08-02 12:09:35.473765+00	2026-08-02 12:13:20.074686+00	\N	\N	4	3	1	MEMBRE_EFFECTIF
3	NGAMIKA	EWIRI	Bienvenu	2014-07-28	KINSHASA	M	CELIBATAIRE	KINSAHSA	0820328100	bienvenu1ngamika@gmail.com	Congolaise	CARTE_ELECTEUR	00001	UNIVERSITAIRE	RAS	f	RAS	Apporter mon apport au parti	t	2026-07-27	adhesions/photos/2026/08/mjthhu.jpg	adhesions/photos/2026/08/mjthhu_NUtHgAc.jpg	VALIDE	A000002		2026-07-27 16:18:27.446+00	2026-08-02 12:15:49.986148+00	\N	\N	1	6	1	MEMBRE_EFFECTIF
7	ILEO	YOKA	Chris	2026-08-05	Kinshasa	M	MARIE	Shaba	24390000002	ileo@gmail.com	Congolaise	CARTE_ELECTEUR	NN0224047	UNIVERSITAIRE	Avocat	f		Servir le pays	t	2026-08-02	adhesions/photos/2026/08/IMG-20260802-WA0135_1.jpg	adhesions/photos/2026/08/IMG-20260802-WA0135_1_NFPiBUo.jpg	VALIDE	000005		2026-08-02 12:32:06.41005+00	2026-08-02 12:32:27.56967+00	\N	\N	23	3	1	MEMBRE_EFFECTIF
4	MATONDO	MADIDI	John	2000-07-29	KINSHASA	M	CELIBATAIRE	KINSHASA GOMBE	0810009355	madidi@gmail.com	Congolaise	CARTE_ELECTEUR	P0003	UNIVERSITAIRE	LIBRE	f		Decouvrir le monde des partis politiques	t	2026-07-29	adhesions/photos/2026/07/ngamika_lpfjRC4.jpeg		REJETE	\N	Manque photo	2026-07-29 16:11:58.995+00	2026-08-02 13:29:40.124931+00	\N	\N	2	3	1	MEMBRE_EFFECTIF
\.


--
-- Data for Name: membership_cartemembre; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.membership_cartemembre (id, numero_carte, date_emission, date_expiration, qr_code, fichier_pdf, actif, membre_id, image_carte) FROM stdin;
1	CARD-2026-000001	2026-08-02	2028-08-01	cartes/qr/2026/08/qr_CARTE_MUKENDI_KABONGO_JEANNE_A000001.png	cartes/pdf/2026/08/CARTE_MUKENDI_KABONGO_JEANNE_A000001.pdf	t	1	cartes/img/2026/08/CARTE_MUKENDI_KABONGO_JEANNE_A000001.png
4	CARD-2026-000003	2026-08-02	2028-08-01	cartes/qr/2026/08/qr_CARTE_MUTOMBO_DISU_ARMAN_A000003.png	cartes/pdf/2026/08/CARTE_MUTOMBO_DISU_ARMAN_A000003.pdf	t	4	cartes/img/2026/08/CARTE_MUTOMBO_DISU_ARMAN_A000003.png
5	CARD-2026-000004	2026-08-02	2028-08-01	cartes/qr/2026/08/qr_CARTE_KAMBANDA_YILA_MERVEILLE_000004.png	cartes/pdf/2026/08/CARTE_KAMBANDA_YILA_MERVEILLE_000004.pdf	t	5	cartes/img/2026/08/CARTE_KAMBANDA_YILA_MERVEILLE_000004.png
3	CARD-2026-000002	2026-08-02	2028-08-01	cartes/qr/2026/08/qr_CARTE_NGAMIKA_EWIRI_BIENVENU_A000002_d828R6J.png	cartes/pdf/2026/08/CARTE_NGAMIKA_EWIRI_BIENVENU_A000002_kSiuzRV.pdf	t	3	cartes/img/2026/08/CARTE_NGAMIKA_EWIRI_BIENVENU_A000002_rDJBeFi.png
6	CARD-2026-000005	2026-08-02	2028-08-01	cartes/qr/2026/08/qr_CARTE_ILEO_YOKA_CHRIS_000005.png	cartes/pdf/2026/08/CARTE_ILEO_YOKA_CHRIS_000005.pdf	t	6	cartes/img/2026/08/CARTE_ILEO_YOKA_CHRIS_000005.png
\.


--
-- Data for Name: membership_membre; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.membership_membre (id, actif, date_activation, notes, adhesion_id) FROM stdin;
1	t	2026-07-27 15:16:52.395+00		1
4	t	2026-08-01 20:38:47.246+00		5
5	t	2026-08-02 12:13:20.075991+00		6
3	t	2026-07-27 16:19:08.534+00	RAS	3
6	t	2026-08-02 12:32:27.571051+00		7
\.


--
-- Data for Name: organisation_affectationpolitique; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.organisation_affectationpolitique (id, role, date_debut, date_fin, actif, notes, commune_id, membre_id, province_id, section_locale_id) FROM stdin;
\.


--
-- Data for Name: organisation_evenement; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.organisation_evenement (id, titre, description, type, date, lieu, participants_attendus, actif, date_creation, organisateur_id, province_id, section_locale_id) FROM stdin;
1	SENSIBILISATION DES MEMBRES SUR LA BONNE CONDUITE	SENSIBILISATION DES MEMBRES SUR LA BONNE CONDUITE	MEETING	2026-07-27 09:00:00+00	STADE DE MARTYR	100000	t	2026-07-27 15:30:07.97+00	1	1	1
2	Meeting de lancement E.C.C.O. — Kinshasa	Grande rencontre de mobilisation pour le lancement des activités du parti à Kinshasa.	MEETING	2026-08-15 22:44:05.783+00	Place du Cinquantenaire, Kinshasa	500	t	2026-08-01 22:44:05.784+00	1	1	1
3	Formation des cadres de section	Session de formation sur l'organisation locale, le recrutement et le suivi des adhesions.	FORMATION	2026-08-29 22:44:05.783+00	Siege Section Ngaliema	80	t	2026-08-01 22:44:05.797+00	1	1	4
\.


--
-- Data for Name: territoires_commune; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.territoires_commune (id, nom, slug, actif, ville_id) FROM stdin;
1	Gombe	gombe	t	1
2	Lingwala	lingwala	t	1
3	Kalamu	kalamu	t	1
4	Ngaliema	ngaliema	t	1
5	Lemba	lemba	t	1
6	Goma	goma	t	2
7	Lubumbashi	lubumbashi	t	3
8	Ibanda	ibanda	t	4
9	Nsele	nsele	t	1
\.


--
-- Data for Name: territoires_province; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.territoires_province (id, nom, code, slug, actif) FROM stdin;
1	Kinshasa	KIN	kinshasa	t
2	Kongo-Central	KOC	kongo-central	t
3	Kwango	KWA	kwango	t
4	Kwilu	KWI	kwilu	t
5	Mai-Ndombe	MND	mai-ndombe	t
6	Kasaï	KAS	kasai	t
7	Kasaï-Central	KAC	kasai-central	t
8	Kasaï-Oriental	KAO	kasai-oriental	t
9	Lomami	LOM	lomami	t
10	Sankuru	SAN	sankuru	t
11	Maniema	MAN	maniema	t
12	Sud-Kivu	SKV	sud-kivu	t
13	Nord-Kivu	NKV	nord-kivu	t
14	Ituri	ITU	ituri	t
15	Haut-Uele	HUE	haut-uele	t
16	Bas-Uele	BUE	bas-uele	t
17	Tshopo	TSH	tshopo	t
18	Tshuapa	TSP	tshuapa	t
19	Mongala	MON	mongala	t
20	Nord-Ubangi	NUB	nord-ubangi	t
21	Sud-Ubangi	SUB	sud-ubangi	t
22	Équateur	EQU	equateur	t
23	Haut-Lomami	HLM	haut-lomami	t
24	Lualaba	LUA	lualaba	t
25	Haut-Katanga	HKT	haut-katanga	t
26	Tanganyika	TAN	tanganyika	t
\.


--
-- Data for Name: territoires_sectionlocale; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.territoires_sectionlocale (id, nom, code, adresse, telephone, actif, latitude, longitude, commune_id) FROM stdin;
1	Section Gombe	KIN-GOM-01	Avenue principale, Gombe		t	-4.325000	15.322000	1
2	Section Lingwala	KIN-LIN-01	Avenue principale, Lingwala		t	-4.325000	15.322000	2
3	Section Kalamu	KIN-KAL-01	Avenue principale, Kalamu		t	-4.325000	15.322000	3
4	Section Ngaliema	KIN-NGA-01	Avenue principale, Ngaliema		t	-4.325000	15.322000	4
5	Section Lemba	KIN-LEM-01	Avenue principale, Lemba		t	-4.325000	15.322000	5
6	Section Goma	NKV-SEC-01			t	\N	\N	6
7	Section Lubumbashi	HKT-SEC-01			t	\N	\N	7
8	Section Ibanda	SKV-SEC-01			t	\N	\N	8
\.


--
-- Data for Name: territoires_ville; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.territoires_ville (id, nom, slug, actif, province_id) FROM stdin;
1	Kinshasa	kinshasa	t	1
2	Goma	goma	t	13
3	Lubumbashi	lubumbashi	t	25
4	Bukavu	bukavu	t	12
\.


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 2, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 72, true);


--
-- Name: core_actionlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_actionlog_id_seq', 42, true);


--
-- Name: core_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_notification_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 18, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 32, true);


--
-- Name: finances_cotisation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.finances_cotisation_id_seq', 3, true);


--
-- Name: membership_adhesion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.membership_adhesion_id_seq', 5, true);


--
-- Name: membership_cartemembre_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.membership_cartemembre_id_seq', 4, true);


--
-- Name: membership_membre_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.membership_membre_id_seq', 4, true);


--
-- Name: organisation_affectationpolitique_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.organisation_affectationpolitique_id_seq', 1, false);


--
-- Name: organisation_evenement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.organisation_evenement_id_seq', 3, true);


--
-- Name: territoires_commune_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.territoires_commune_id_seq', 9, true);


--
-- Name: territoires_province_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.territoires_province_id_seq', 26, true);


--
-- Name: territoires_sectionlocale_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.territoires_sectionlocale_id_seq', 8, true);


--
-- Name: territoires_ville_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.territoires_ville_id_seq', 4, true);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: core_actionlog core_actionlog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_actionlog
    ADD CONSTRAINT core_actionlog_pkey PRIMARY KEY (id);


--
-- Name: core_notification core_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_notification
    ADD CONSTRAINT core_notification_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: finances_cotisation finances_cotisation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.finances_cotisation
    ADD CONSTRAINT finances_cotisation_pkey PRIMARY KEY (id);


--
-- Name: membership_adhesion membership_adhesion_numero_membre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_adhesion
    ADD CONSTRAINT membership_adhesion_numero_membre_key UNIQUE (numero_membre);


--
-- Name: membership_adhesion membership_adhesion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_adhesion
    ADD CONSTRAINT membership_adhesion_pkey PRIMARY KEY (id);


--
-- Name: membership_cartemembre membership_cartemembre_membre_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_cartemembre
    ADD CONSTRAINT membership_cartemembre_membre_id_key UNIQUE (membre_id);


--
-- Name: membership_cartemembre membership_cartemembre_numero_carte_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_cartemembre
    ADD CONSTRAINT membership_cartemembre_numero_carte_key UNIQUE (numero_carte);


--
-- Name: membership_cartemembre membership_cartemembre_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_cartemembre
    ADD CONSTRAINT membership_cartemembre_pkey PRIMARY KEY (id);


--
-- Name: membership_membre membership_membre_adhesion_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_membre
    ADD CONSTRAINT membership_membre_adhesion_id_key UNIQUE (adhesion_id);


--
-- Name: membership_membre membership_membre_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_membre
    ADD CONSTRAINT membership_membre_pkey PRIMARY KEY (id);


--
-- Name: organisation_affectationpolitique organisation_affectationpolitique_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organisation_affectationpolitique
    ADD CONSTRAINT organisation_affectationpolitique_pkey PRIMARY KEY (id);


--
-- Name: organisation_evenement organisation_evenement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organisation_evenement
    ADD CONSTRAINT organisation_evenement_pkey PRIMARY KEY (id);


--
-- Name: territoires_commune territoires_commune_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territoires_commune
    ADD CONSTRAINT territoires_commune_pkey PRIMARY KEY (id);


--
-- Name: territoires_commune territoires_commune_ville_id_nom_e78b6696_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territoires_commune
    ADD CONSTRAINT territoires_commune_ville_id_nom_e78b6696_uniq UNIQUE (ville_id, nom);


--
-- Name: territoires_province territoires_province_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territoires_province
    ADD CONSTRAINT territoires_province_code_key UNIQUE (code);


--
-- Name: territoires_province territoires_province_nom_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territoires_province
    ADD CONSTRAINT territoires_province_nom_key UNIQUE (nom);


--
-- Name: territoires_province territoires_province_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territoires_province
    ADD CONSTRAINT territoires_province_pkey PRIMARY KEY (id);


--
-- Name: territoires_province territoires_province_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territoires_province
    ADD CONSTRAINT territoires_province_slug_key UNIQUE (slug);


--
-- Name: territoires_sectionlocale territoires_sectionlocale_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territoires_sectionlocale
    ADD CONSTRAINT territoires_sectionlocale_code_key UNIQUE (code);


--
-- Name: territoires_sectionlocale territoires_sectionlocale_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territoires_sectionlocale
    ADD CONSTRAINT territoires_sectionlocale_pkey PRIMARY KEY (id);


--
-- Name: territoires_ville territoires_ville_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territoires_ville
    ADD CONSTRAINT territoires_ville_pkey PRIMARY KEY (id);


--
-- Name: territoires_ville territoires_ville_province_id_nom_c4aa0ad3_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territoires_ville
    ADD CONSTRAINT territoires_ville_province_id_nom_c4aa0ad3_uniq UNIQUE (province_id, nom);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_province_id_d2154404; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_province_id_d2154404 ON public.accounts_user USING btree (province_id);


--
-- Name: accounts_user_role_57e97df0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_role_57e97df0 ON public.accounts_user USING btree (role);


--
-- Name: accounts_user_role_57e97df0_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_role_57e97df0_like ON public.accounts_user USING btree (role varchar_pattern_ops);


--
-- Name: accounts_user_section_locale_id_66ed90bb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_section_locale_id_66ed90bb ON public.accounts_user USING btree (section_locale_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: core_actionlog_user_id_686d25e2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_actionlog_user_id_686d25e2 ON public.core_actionlog USING btree (user_id);


--
-- Name: core_notification_destinataire_id_00606b07; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_notification_destinataire_id_00606b07 ON public.core_notification USING btree (destinataire_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: finances_cotisation_enregistre_par_id_2fd9ea5b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX finances_cotisation_enregistre_par_id_2fd9ea5b ON public.finances_cotisation USING btree (enregistre_par_id);


--
-- Name: finances_cotisation_membre_id_340abff4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX finances_cotisation_membre_id_340abff4 ON public.finances_cotisation USING btree (membre_id);


--
-- Name: membership_adhesion_numero_membre_110b5d6f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX membership_adhesion_numero_membre_110b5d6f_like ON public.membership_adhesion USING btree (numero_membre varchar_pattern_ops);


--
-- Name: membership_adhesion_province_origine_id_b218525f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX membership_adhesion_province_origine_id_b218525f ON public.membership_adhesion USING btree (province_origine_id);


--
-- Name: membership_adhesion_section_locale_id_c9963e11; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX membership_adhesion_section_locale_id_c9963e11 ON public.membership_adhesion USING btree (section_locale_id);


--
-- Name: membership_adhesion_statut_c70addd9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX membership_adhesion_statut_c70addd9 ON public.membership_adhesion USING btree (statut);


--
-- Name: membership_adhesion_statut_c70addd9_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX membership_adhesion_statut_c70addd9_like ON public.membership_adhesion USING btree (statut varchar_pattern_ops);


--
-- Name: membership_adhesion_valide_par_id_7154a675; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX membership_adhesion_valide_par_id_7154a675 ON public.membership_adhesion USING btree (valide_par_id);


--
-- Name: membership_cartemembre_numero_carte_3c277e81_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX membership_cartemembre_numero_carte_3c277e81_like ON public.membership_cartemembre USING btree (numero_carte varchar_pattern_ops);


--
-- Name: membership_membre_actif_dfb2d723; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX membership_membre_actif_dfb2d723 ON public.membership_membre USING btree (actif);


--
-- Name: organisation_affectationpolitique_commune_id_c87333d4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX organisation_affectationpolitique_commune_id_c87333d4 ON public.organisation_affectationpolitique USING btree (commune_id);


--
-- Name: organisation_affectationpolitique_membre_id_62b8575b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX organisation_affectationpolitique_membre_id_62b8575b ON public.organisation_affectationpolitique USING btree (membre_id);


--
-- Name: organisation_affectationpolitique_province_id_8be82c94; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX organisation_affectationpolitique_province_id_8be82c94 ON public.organisation_affectationpolitique USING btree (province_id);


--
-- Name: organisation_affectationpolitique_section_locale_id_0ff80905; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX organisation_affectationpolitique_section_locale_id_0ff80905 ON public.organisation_affectationpolitique USING btree (section_locale_id);


--
-- Name: organisation_evenement_organisateur_id_8e9bc127; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX organisation_evenement_organisateur_id_8e9bc127 ON public.organisation_evenement USING btree (organisateur_id);


--
-- Name: organisation_evenement_province_id_150bc92a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX organisation_evenement_province_id_150bc92a ON public.organisation_evenement USING btree (province_id);


--
-- Name: organisation_evenement_section_locale_id_64cdbfb4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX organisation_evenement_section_locale_id_64cdbfb4 ON public.organisation_evenement USING btree (section_locale_id);


--
-- Name: territoires_commune_slug_7678e350; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX territoires_commune_slug_7678e350 ON public.territoires_commune USING btree (slug);


--
-- Name: territoires_commune_slug_7678e350_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX territoires_commune_slug_7678e350_like ON public.territoires_commune USING btree (slug varchar_pattern_ops);


--
-- Name: territoires_commune_ville_id_58b227e4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX territoires_commune_ville_id_58b227e4 ON public.territoires_commune USING btree (ville_id);


--
-- Name: territoires_province_code_5d126df3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX territoires_province_code_5d126df3_like ON public.territoires_province USING btree (code varchar_pattern_ops);


--
-- Name: territoires_province_nom_7ca95abc_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX territoires_province_nom_7ca95abc_like ON public.territoires_province USING btree (nom varchar_pattern_ops);


--
-- Name: territoires_province_slug_77a5a547_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX territoires_province_slug_77a5a547_like ON public.territoires_province USING btree (slug varchar_pattern_ops);


--
-- Name: territoires_sectionlocale_code_983d2e61_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX territoires_sectionlocale_code_983d2e61_like ON public.territoires_sectionlocale USING btree (code varchar_pattern_ops);


--
-- Name: territoires_sectionlocale_commune_id_75a11dd6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX territoires_sectionlocale_commune_id_75a11dd6 ON public.territoires_sectionlocale USING btree (commune_id);


--
-- Name: territoires_ville_province_id_8a11caaf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX territoires_ville_province_id_8a11caaf ON public.territoires_ville USING btree (province_id);


--
-- Name: territoires_ville_slug_e987d7de; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX territoires_ville_slug_e987d7de ON public.territoires_ville USING btree (slug);


--
-- Name: territoires_ville_slug_e987d7de_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX territoires_ville_slug_e987d7de_like ON public.territoires_ville USING btree (slug varchar_pattern_ops);


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user accounts_user_province_id_d2154404_fk_territoires_province_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_province_id_d2154404_fk_territoires_province_id FOREIGN KEY (province_id) REFERENCES public.territoires_province(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user accounts_user_section_locale_id_66ed90bb_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_section_locale_id_66ed90bb_fk_territoir FOREIGN KEY (section_locale_id) REFERENCES public.territoires_sectionlocale(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_actionlog core_actionlog_user_id_686d25e2_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_actionlog
    ADD CONSTRAINT core_actionlog_user_id_686d25e2_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_notification core_notification_destinataire_id_00606b07_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_notification
    ADD CONSTRAINT core_notification_destinataire_id_00606b07_fk_accounts_user_id FOREIGN KEY (destinataire_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finances_cotisation finances_cotisation_enregistre_par_id_2fd9ea5b_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.finances_cotisation
    ADD CONSTRAINT finances_cotisation_enregistre_par_id_2fd9ea5b_fk_accounts_ FOREIGN KEY (enregistre_par_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finances_cotisation finances_cotisation_membre_id_340abff4_fk_membership_membre_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.finances_cotisation
    ADD CONSTRAINT finances_cotisation_membre_id_340abff4_fk_membership_membre_id FOREIGN KEY (membre_id) REFERENCES public.membership_membre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: membership_adhesion membership_adhesion_province_origine_id_b218525f_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_adhesion
    ADD CONSTRAINT membership_adhesion_province_origine_id_b218525f_fk_territoir FOREIGN KEY (province_origine_id) REFERENCES public.territoires_province(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: membership_adhesion membership_adhesion_section_locale_id_c9963e11_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_adhesion
    ADD CONSTRAINT membership_adhesion_section_locale_id_c9963e11_fk_territoir FOREIGN KEY (section_locale_id) REFERENCES public.territoires_sectionlocale(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: membership_adhesion membership_adhesion_valide_par_id_7154a675_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_adhesion
    ADD CONSTRAINT membership_adhesion_valide_par_id_7154a675_fk_accounts_user_id FOREIGN KEY (valide_par_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: membership_cartemembre membership_cartememb_membre_id_6cc7744b_fk_membershi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_cartemembre
    ADD CONSTRAINT membership_cartememb_membre_id_6cc7744b_fk_membershi FOREIGN KEY (membre_id) REFERENCES public.membership_membre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: membership_membre membership_membre_adhesion_id_b8b5b2bc_fk_membershi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.membership_membre
    ADD CONSTRAINT membership_membre_adhesion_id_b8b5b2bc_fk_membershi FOREIGN KEY (adhesion_id) REFERENCES public.membership_adhesion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: organisation_affectationpolitique organisation_affecta_commune_id_c87333d4_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organisation_affectationpolitique
    ADD CONSTRAINT organisation_affecta_commune_id_c87333d4_fk_territoir FOREIGN KEY (commune_id) REFERENCES public.territoires_commune(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: organisation_affectationpolitique organisation_affecta_membre_id_62b8575b_fk_membershi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organisation_affectationpolitique
    ADD CONSTRAINT organisation_affecta_membre_id_62b8575b_fk_membershi FOREIGN KEY (membre_id) REFERENCES public.membership_membre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: organisation_affectationpolitique organisation_affecta_province_id_8be82c94_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organisation_affectationpolitique
    ADD CONSTRAINT organisation_affecta_province_id_8be82c94_fk_territoir FOREIGN KEY (province_id) REFERENCES public.territoires_province(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: organisation_affectationpolitique organisation_affecta_section_locale_id_0ff80905_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organisation_affectationpolitique
    ADD CONSTRAINT organisation_affecta_section_locale_id_0ff80905_fk_territoir FOREIGN KEY (section_locale_id) REFERENCES public.territoires_sectionlocale(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: organisation_evenement organisation_eveneme_organisateur_id_8e9bc127_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organisation_evenement
    ADD CONSTRAINT organisation_eveneme_organisateur_id_8e9bc127_fk_accounts_ FOREIGN KEY (organisateur_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: organisation_evenement organisation_eveneme_province_id_150bc92a_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organisation_evenement
    ADD CONSTRAINT organisation_eveneme_province_id_150bc92a_fk_territoir FOREIGN KEY (province_id) REFERENCES public.territoires_province(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: organisation_evenement organisation_eveneme_section_locale_id_64cdbfb4_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.organisation_evenement
    ADD CONSTRAINT organisation_eveneme_section_locale_id_64cdbfb4_fk_territoir FOREIGN KEY (section_locale_id) REFERENCES public.territoires_sectionlocale(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: territoires_commune territoires_commune_ville_id_58b227e4_fk_territoires_ville_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territoires_commune
    ADD CONSTRAINT territoires_commune_ville_id_58b227e4_fk_territoires_ville_id FOREIGN KEY (ville_id) REFERENCES public.territoires_ville(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: territoires_sectionlocale territoires_sectionl_commune_id_75a11dd6_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territoires_sectionlocale
    ADD CONSTRAINT territoires_sectionl_commune_id_75a11dd6_fk_territoir FOREIGN KEY (commune_id) REFERENCES public.territoires_commune(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: territoires_ville territoires_ville_province_id_8a11caaf_fk_territoir; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.territoires_ville
    ADD CONSTRAINT territoires_ville_province_id_8a11caaf_fk_territoir FOREIGN KEY (province_id) REFERENCES public.territoires_province(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: TABLE accounts_user; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.accounts_user TO eparti_user;


--
-- Name: TABLE accounts_user_groups; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.accounts_user_groups TO eparti_user;


--
-- Name: SEQUENCE accounts_user_groups_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.accounts_user_groups_id_seq TO eparti_user;


--
-- Name: SEQUENCE accounts_user_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.accounts_user_id_seq TO eparti_user;


--
-- Name: TABLE accounts_user_user_permissions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.accounts_user_user_permissions TO eparti_user;


--
-- Name: SEQUENCE accounts_user_user_permissions_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.accounts_user_user_permissions_id_seq TO eparti_user;


--
-- Name: TABLE auth_group; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.auth_group TO eparti_user;


--
-- Name: SEQUENCE auth_group_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.auth_group_id_seq TO eparti_user;


--
-- Name: TABLE auth_group_permissions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.auth_group_permissions TO eparti_user;


--
-- Name: SEQUENCE auth_group_permissions_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.auth_group_permissions_id_seq TO eparti_user;


--
-- Name: TABLE auth_permission; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.auth_permission TO eparti_user;


--
-- Name: SEQUENCE auth_permission_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.auth_permission_id_seq TO eparti_user;


--
-- Name: TABLE core_actionlog; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.core_actionlog TO eparti_user;


--
-- Name: SEQUENCE core_actionlog_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.core_actionlog_id_seq TO eparti_user;


--
-- Name: TABLE core_notification; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.core_notification TO eparti_user;


--
-- Name: SEQUENCE core_notification_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.core_notification_id_seq TO eparti_user;


--
-- Name: TABLE django_admin_log; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.django_admin_log TO eparti_user;


--
-- Name: SEQUENCE django_admin_log_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.django_admin_log_id_seq TO eparti_user;


--
-- Name: TABLE django_content_type; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.django_content_type TO eparti_user;


--
-- Name: SEQUENCE django_content_type_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.django_content_type_id_seq TO eparti_user;


--
-- Name: TABLE django_migrations; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.django_migrations TO eparti_user;


--
-- Name: SEQUENCE django_migrations_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.django_migrations_id_seq TO eparti_user;


--
-- Name: TABLE django_session; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.django_session TO eparti_user;


--
-- Name: TABLE membership_cartemembre; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.membership_cartemembre TO eparti_user;


--
-- Name: SEQUENCE membership_cartemembre_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.membership_cartemembre_id_seq TO eparti_user;


--
-- Name: TABLE membership_membre; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.membership_membre TO eparti_user;


--
-- Name: SEQUENCE membership_membre_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.membership_membre_id_seq TO eparti_user;


--
-- Name: TABLE organisation_affectationpolitique; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.organisation_affectationpolitique TO eparti_user;


--
-- Name: SEQUENCE organisation_affectationpolitique_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.organisation_affectationpolitique_id_seq TO eparti_user;


--
-- Name: TABLE organisation_evenement; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.organisation_evenement TO eparti_user;


--
-- Name: SEQUENCE organisation_evenement_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.organisation_evenement_id_seq TO eparti_user;


--
-- Name: TABLE territoires_commune; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.territoires_commune TO eparti_user;


--
-- Name: SEQUENCE territoires_commune_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.territoires_commune_id_seq TO eparti_user;


--
-- Name: TABLE territoires_province; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.territoires_province TO eparti_user;


--
-- Name: SEQUENCE territoires_province_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.territoires_province_id_seq TO eparti_user;


--
-- Name: TABLE territoires_sectionlocale; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.territoires_sectionlocale TO eparti_user;


--
-- Name: SEQUENCE territoires_sectionlocale_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.territoires_sectionlocale_id_seq TO eparti_user;


--
-- Name: TABLE territoires_ville; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.territoires_ville TO eparti_user;


--
-- Name: SEQUENCE territoires_ville_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.territoires_ville_id_seq TO eparti_user;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO eparti_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO eparti_user;


--
-- PostgreSQL database dump complete
--

\unrestrict Gn0f6b4oKEayeu2Omi6mJdjHVaI2ECk3avyYgGpCRvCqI18uKdyw6bb7MGaDqa1

