# Generated by Django 5.2.16 on 2026-07-27 15:15

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('territoires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('post_nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('etat_civil', models.CharField(choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('DIVORCE', 'Divorcé(e)'), ('VEUF', 'Veuf / Veuve'), ('UNION_LIBRE', 'Union libre')], max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nationalite', models.CharField(default='Congolaise', max_length=80)),
                ('type_piece_identite', models.CharField(choices=[('CARTE_ELECTEUR', "Carte d'électeur"), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de conduire'), ('AUTRE', 'Autre')], default='CARTE_ELECTEUR', max_length=20)),
                ('numero_piece_identite', models.CharField(max_length=80)),
                ('niveau_etudes', models.CharField(blank=True, choices=[('SANS', 'Sans niveau'), ('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire'), ('UNIVERSITAIRE', 'Universitaire'), ('POST_UNIV', 'Post-universitaire')], max_length=20)),
                ('profession', models.CharField(blank=True, max_length=120)),
                ('deja_membre', models.BooleanField(default=False, verbose_name='Déjà membre auparavant ?')),
                ('details_membre', models.TextField(blank=True)),
                ('motivations', models.TextField()),
                ('certifie_exactitude', models.BooleanField(default=False)),
                ('date_signature', models.DateField(default=datetime.date.today)),
                ('photo1', models.ImageField(blank=True, upload_to='adhesions/photos/%Y/%m/', verbose_name="Photo d'identité")),
                ('photo2', models.ImageField(blank=True, upload_to='adhesions/photos/%Y/%m/', verbose_name='Photo supplémentaire')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validée'), ('REJETE', 'Rejetée')], db_index=True, default='EN_ATTENTE', max_length=15)),
                ('numero_membre', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('province_origine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhesions_origine', to='territoires.province', verbose_name="Province d'origine")),
                ('section_locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhesions', to='territoires.sectionlocale')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adhesions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adhésion',
                'verbose_name_plural': 'Adhésions',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('date_activation', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('adhesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membre', to='membership.adhesion')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['-date_activation'],
            },
        ),
        migrations.CreateModel(
            name='CarteMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte', models.CharField(db_index=True, max_length=40, unique=True)),
                ('date_emission', models.DateField(default=datetime.date.today)),
                ('date_expiration', models.DateField()),
                ('qr_code', models.ImageField(blank=True, upload_to='cartes/qr/%Y/%m/')),
                ('fichier_pdf', models.FileField(blank=True, upload_to='cartes/pdf/%Y/%m/')),
                ('actif', models.BooleanField(default=True)),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte', to='membership.membre')),
            ],
            options={
                'verbose_name': 'Carte de membre',
                'verbose_name_plural': 'Cartes de membre',
                'ordering': ['-date_emission'],
            },
        ),
    ]
