# Generated by Django 5.2.16 on 2026-07-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartemembre',
            name='image_carte',
            field=models.ImageField(blank=True, upload_to='cartes/img/%Y/%m/', verbose_name='Aperçu carte'),
        ),
    ]
