# Generated by Django 5.2.16 on 2026-07-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_cartemembre_image_carte'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion',
            name='domaine',
            field=models.CharField(blank=True, help_text='Ex. : Domaine, avenue, cellule locale', max_length=120, verbose_name='Domaine / quartier'),
        ),
        migrations.AddField(
            model_name='adhesion',
            name='federation',
            field=models.CharField(blank=True, help_text='Ex. : Tshangu — sinon dérivée de la section', max_length=120, verbose_name='Fédération'),
        ),
        migrations.AddField(
            model_name='adhesion',
            name='secteur',
            field=models.CharField(blank=True, help_text='Ex. : Nsele — sinon dérivé de la commune', max_length=120, verbose_name='Secteur'),
        ),
        migrations.AddField(
            model_name='cartemembre',
            name='numero_id_affiche',
            field=models.CharField(blank=True, help_text='Identifiant numérique affiché sous la photo (ex. 12020222251631)', max_length=30, verbose_name='N° ID imprimé'),
        ),
    ]
