# Generated by Django 5.2.16 on 2026-07-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_adhesion_domaine_adhesion_federation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhesion',
            name='domaine',
        ),
        migrations.RemoveField(
            model_name='adhesion',
            name='federation',
        ),
        migrations.RemoveField(
            model_name='adhesion',
            name='secteur',
        ),
        migrations.RemoveField(
            model_name='cartemembre',
            name='numero_id_affiche',
        ),
    ]
