# Generated by Django 5.0.4 on 2026-08-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_normalize_numero_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion',
            name='qualite',
            field=models.CharField(choices=[('MEMBRE_EFFECTIF', 'Membre effectif'), ('CADRE', 'Cadre'), ('HAUT_CADRE', 'Haut cadre'), ('MEMBRE_HONNEUR', "Membre d'honneur")], default='MEMBRE_EFFECTIF', max_length=20, verbose_name='Qualité'),
        ),
    ]
