# Generated by Django 5.2.16 on 2026-07-27 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        ('territoires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationPolitique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COORDINATEUR', 'Coordinateur'), ('MOBILISATEUR', 'Mobilisateur'), ('SECRETAIRE', 'Secrétaire'), ('TRESORIER', 'Trésorier'), ('PRESIDENT_SECTION', 'Président de section'), ('AUTRE', 'Autre')], max_length=30)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='territoires.commune')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='membership.membre')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='territoires.province')),
                ('section_locale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='territoires.sectionlocale')),
            ],
            options={
                'verbose_name': 'Affectation politique',
                'verbose_name_plural': 'Affectations politiques',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('MEETING', 'Meeting'), ('MOBILISATION', 'Mobilisation'), ('FORMATION', 'Formation'), ('ASSEMBLEE', 'Assemblée'), ('AUTRE', 'Autre')], default='MEETING', max_length=20)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('participants_attendus', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('organisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_organises', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='territoires.province')),
                ('section_locale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='territoires.sectionlocale')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date'],
            },
        ),
    ]
