# Generated by Django 5.2.16 on 2026-07-27 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='CDF', max_length=5)),
                ('date_paiement', models.DateField()),
                ('type', models.CharField(choices=[('adhesion', "Frais d'adhésion"), ('mensuelle', 'Cotisation mensuelle'), ('don', 'Don'), ('exceptionnelle', 'Cotisation exceptionnelle')], default='mensuelle', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('mode_paiement', models.CharField(blank=True, help_text='Espèces, Mobile Money, Banque…', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='membership.membre')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-date_paiement', '-date_creation'],
            },
        ),
    ]
