# Generated by Django 5.2.16 on 2026-08-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='devise',
            field=models.CharField(choices=[('CDF', 'Franc congolais (CDF)'), ('USD', 'Dollar américain (USD)'), ('EUR', 'Euro (EUR)')], default='CDF', max_length=5),
        ),
    ]
