# Generated by Django 5.2.16 on 2026-08-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_mode_paiement_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='preuve',
            field=models.ImageField(blank=True, help_text="Capture d'écran, reçu ou photo du paiement", null=True, upload_to='cotisations/preuves/%Y/%m/', verbose_name='Preuve de paiement'),
        ),
    ]
